FROM python:3.13-slim

WORKDIR /app

COPY integrations/restate/aws/handler/handler.py /app/handler.py

RUN pip install --no-cache-dir "restate_sdk[serde]" hypercorn

EXPOSE 9080

ENTRYPOINT ["python", "/app/handler.py"]
